# Generated by Django 5.0.7 on 2024-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collcover',
            field=models.CharField(max_length=2000),
        ),
    ]
